// components/DynamicIcon.tsx
import * as LucideIcons from 'lucide-react'

interface DynamicIconProps {
  name: string
  className?: string
}

export function DynamicIcon({ name, className = 'w-6 h-6' }: DynamicIconProps) {
  // Ambil komponen ikon secara dinamis dari lucide-react berdasarkan string namanya
  const IconComponent = (LucideIcons as any)[name] || LucideIcons.Briefcase

  return <IconComponent className={className} />
}

// Daftar Ikon Lengkap yang Mendukung Render Dinamis
export const AVAILABLE_ICONS = [
  { label: 'Briefcase', value: 'Briefcase' },
  { label: 'Shield', value: 'Shield' },
  { label: 'Wrench', value: 'Wrench' },
  { label: 'Building', value: 'Building' },
  { label: 'Users', value: 'Users' },
  { label: 'Settings', value: 'Settings' },
  { label: 'Truck', value: 'Truck' },
  { label: 'Globe', value: 'Globe' },
  { label: 'Award', value: 'Award' },
  { label: 'Check Circle', value: 'CheckCircle' },
  { label: 'Clock', value: 'Clock' },
  { label: 'Dollar Sign', value: 'DollarSign' },
  { label: 'File Text', value: 'FileText' },
  { label: 'Headphones', value: 'Headphones' },
  { label: 'Heart', value: 'Heart' },
  { label: 'Home', value: 'Home' },
  { label: 'Layers', value: 'Layers' },
  { label: 'Lock', value: 'Lock' },
  { label: 'Mail', value: 'Mail' },
  { label: 'Map Pin', value: 'MapPin' },
  { label: 'Monitor', value: 'Monitor' },
  { label: 'Package', value: 'Package' },
  { label: 'Phone', value: 'Phone' },
  { label: 'Pie Chart', value: 'PieChart' },
  { label: 'Search', value: 'Search' },
  { label: 'Star', value: 'Star' },
  { label: 'Target', value: 'Target' },
  { label: 'Trending Up', value: 'TrendingUp' },
  { label: 'Cpu', value: 'Cpu' },
  { label: 'Database', value: 'Database' },
  { label: 'Server', value: 'Server' },
  { label: 'Smartphone', value: 'Smartphone' },
  { label: 'Compass', value: 'Compass' },
  { label: 'Key', value: 'Key' },
  { label: 'Map', value: 'Map' },
  { label: 'Shield Check', value: 'ShieldCheck' },
  { label: 'Activity', value: 'Activity' },
  { label: 'Archive', value: 'Archive' },
  { label: 'Bar Chart', value: 'BarChart' },
  { label: 'Bookmark', value: 'Bookmark' },
  { label: 'Camera', value: 'Camera' },
  { label: 'Cloud', value: 'Cloud' },
  { label: 'Code', value: 'Code' },
  { label: 'Coffee', value: 'Coffee' },
  { label: 'Credit Card', value: 'CreditCard' },
  { label: 'Download', value: 'Download' },
  { label: 'Edit', value: 'Edit' },
  { label: 'Eye', value: 'Eye' },
  { label: 'Filter', value: 'Filter' },
  { label: 'Flag', value: 'Flag' },
  { label: 'Folder', value: 'Folder' },
  { label: 'Gift', value: 'Gift' },
  { label: 'Grid', value: 'Grid' },
  { label: 'Image', value: 'Image' },
  { label: 'Info', value: 'Info' },
  { label: 'List', value: 'List' },
  { label: 'Music', value: 'Music' },
  { label: 'Paperclip', value: 'Paperclip' },
  { label: 'Play', value: 'Play' },
  { label: 'Power', value: 'Power' },
  { label: 'Refresh', value: 'RefreshCw' },
  { label: 'Save', value: 'Save' },
  { label: 'Send', value: 'Send' },
  { label: 'Share', value: 'Share' },
  { label: 'Shopping Bag', value: 'ShoppingBag' },
  { label: 'Shopping Cart', value: 'ShoppingCart' },
  { label: 'Smile', value: 'Smile' },
  { label: 'Speaker', value: 'Speaker' },
  { label: 'Sun', value: 'Sun' },
  { label: 'Terminal', value: 'Terminal' },
  { label: 'Tool', value: 'Tool' },
  { label: 'Trash', value: 'Trash' },
  { label: 'Unlock', value: 'Unlock' },
  { label: 'Upload', value: 'Upload' },
  { label: 'User', value: 'User' },
  { label: 'Video', value: 'Video' },
  { label: 'Volume', value: 'Volume' },
  { label: 'Watch', value: 'Watch' },
  { label: 'Wifi', value: 'Wifi' },
  { label: 'Zap', value: 'Zap' },
  { label: 'Anchor', value: 'Anchor' },
  { label: 'Bell', value: 'Bell' },
  { label: 'Book', value: 'Book' },
  { label: 'Calendar', value: 'Calendar' },
  { label: 'Check', value: 'Check' },
  { label: 'Copy', value: 'Copy' },
  { label: 'Disc', value: 'Disc' },
  { label: 'Feather', value: 'Feather' },
  { label: 'Film', value: 'Film' },
  { label: 'Hash', value: 'Hash' },
  { label: 'Help Circle', value: 'HelpCircle' },
  { label: 'Inbox', value: 'Inbox' },
  { label: 'Life Buoy', value: 'LifeBuoy' },
  { label: 'Link', value: 'Link' },
  { label: 'Maximize', value: 'Maximize' },
  { label: 'Minimize', value: 'Minimize' },
  { label: 'Moon', value: 'Moon' },
  { label: 'Navigation', value: 'Navigation' },
  { label: 'Percent', value: 'Percent' },
  { label: 'Printer', value: 'Printer' },
  { label: 'Radio', value: 'Radio' },
  { label: 'Repeat', value: 'Repeat' },
  { label: 'Scissors', value: 'Scissors' },
  { label: 'Sidebar', value: 'Sidebar' },
  { label: 'Sliders', value: 'Sliders' },
  { label: 'Square', value: 'Square' },
  { label: 'Stop Circle', value: 'StopCircle' },
  { label: 'Sunrise', value: 'Sunrise' },
  { label: 'Sunset', value: 'Sunset' },
  { label: 'Tablet', value: 'Tablet' },
  { label: 'Tag', value: 'Tag' },
  { label: 'Thermometer', value: 'Thermometer' },
  { label: 'Thumbs Down', value: 'ThumbsDown' },
  { label: 'Thumbs Up', value: 'ThumbsUp' },
  { label: 'Toggle Left', value: 'ToggleLeft' },
  { label: 'Toggle Right', value: 'ToggleRight' },
  { label: 'Trending Down', value: 'TrendingDown' },
  { label: 'Triangle', value: 'Triangle' },
  { label: 'TV', value: 'Tv' },
  { label: 'Umbrella', value: 'Umbrella' },
  { label: 'Underline', value: 'Underline' },
  { label: 'Video Off', value: 'VideoOff' },
  { label: 'Volume X', value: 'VolumeX' },
  { label: 'Zoom In', value: 'ZoomIn' },
  { label: 'Zoom Out', value: 'ZoomOut' }
]